baseurl = "https://www.yuchanns.xyz/"
languageCode = "zh-CN"
title = "代码炼金工坊"
theme = "goblog"
# googleAnalytics = ""
# disqusShortname = ""
#disableKinds = ["taxonomy", "term", "section", "404"]
copyright = "代码炼金工坊 © 2016-<span id=\"year\"></span><script type=\"text/javascript\">var d = new Date(); document.getElementById('year').innerHTML=d.getFullYear();</script> | <a href=\"http://www.beian.miit.gov.cn/\">闽ICP备2020021086号-1</a>"

[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "Awesome"
#    url = "/awesome/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/yuchanns"

[params]
    mainSections = ["post"]

    description = "追寻计算机炼金术的贤者之石"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    enableGitalk = true

    [params.logo]
    url = "yuchanns.jpg"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

    [[params.menu]]
        name = "About"
        url = "/about/"
    [[params.menu]]
        name = "Awesome"
        url = "/awesome/"
    [[params.menu]]
        name = "GitHub"
        url = "https://github.com/yuchanns"

    [params.Gitalk]
        clientID = "6ea1fac9111c65d9cd1b" # Your client ID
        clientSecret = "c5d0f8af8a0d5bf37214d711da4b6811c79aea3f" # Your client secret
        repo = "yuchanns" # The repo to store comments
        owner = "yuchanns" # Your GitHub ID
        admin= "yuchanns" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
        id= "location.pathname" # The unique id of the page.
        labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
        perPage= 15 # Pagination size, with maximum 100.
        pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
        createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
        distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
