baseurl = "https://www.yuchanns.xyz/"
languageCode = "zh-CN"
title = "代码炼金工坊"
theme = "goblog"
# googleAnalytics = ""
# disqusShortname = ""
#disableKinds = ["taxonomy", "term", "section", "404"]
copyright = "代码炼金工坊 © 2016-<span id=\"year\"></span><script type=\"text/javascript\">var d = new Date(); document.getElementById('year').innerHTML=d.getFullYear();</script> | <a href=\"http://www.beian.miit.gov.cn/\">闽ICP备2020021086号-1</a>"

[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "Awesome"
#    url = "/awesome/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/yuchanns"

[params]
    mainSections = ["post"]

    description = "追寻计算机炼金术的贤者之石"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "yuchanns.jpg"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

    [[params.menu]]
        name = "About"
        url = "/about/"
    [[params.menu]]
        name = "Awesome"
        url = "/awesome/"
    [[params.menu]]
        name = "GitHub"
        url = "https://github.com/yuchanns"
