baseurl = "https://yuchanns.xyz/"
languageCode = "zh-CN"
title = "代码炼金工坊"
theme = "lithium"
# googleAnalytics = ""
# disqusShortname = ""
disableKinds = ["taxonomy", "term", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Awesome"
    url = "/awesome/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yuchanns"

[params]
    mainSections = ["post"]

    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "yuchanns.jpg"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"
