name: blog

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
defaults:
  run:
    working-directory: src
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }}
      TCB_API_KEY: ${{ secrets.TCB_API_KEY }}
      TCB_ENV_ID: ${{ secrets.ATELIER_ENV_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build
        run: hugo --minify
      - name: TCB install
        run: yarn global add @cloudbase/cli
      - name: TCB login
        run: $(yarn global bin)/tcb login --apiKeyId $TCB_API_KEY_ID --apiKey $TCB_API_KEY
      - name: TCB clean
        run: |
          yes | $(yarn global bin)/tcb hosting delete -e $TCB_ENV_ID
      - name: TCB publish
        run: $(yarn global bin)/tcb hosting deploy -e $TCB_ENV_ID public