name: blog

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/blog.yml'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }}
      TCB_API_KEY: ${{ secrets.TCB_API_KEY }}
      TCB_ENV_ID: ${{ secrets.ATELIER_ENV_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install Packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y build-essential
      - name: Cache go modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules-blog
        with:
          path: pre-render/vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Build
        working-directory: src
        run: hugo --minify
      - name: Pre-render and Trim Script Tags
        working-directory: pre-render
        run: |
          go build -o hugoprerender
          ./hugoprerender -d=../src/public -x=.html
      - name: Upload Sitemap
        uses: actions/upload-artifact@v2
        with:
          name: blog-sitemap
          path: src/public/sitemap.xml
      - name: TCB install
        run: yarn global add @cloudbase/cli
      - name: TCB login
        run: $(yarn global bin)/tcb login --apiKeyId $TCB_API_KEY_ID --apiKey $TCB_API_KEY
      - name: TCB clean
        run: |
          yes | $(yarn global bin)/tcb hosting delete -e $TCB_ENV_ID
      - name: TCB publish
        working-directory: src
        run: $(yarn global bin)/tcb hosting deploy -e $TCB_ENV_ID public